config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :planes do
    resources :rentals, except: :destroy
  end
  resources :rentals, only: :destroy

  get 'dashboard', to: 'dashboard#show'
end



# get 'planes', to: 'planes#index'
# get 'planes/id', to: 'planes#show'
# post 'planes/id', to: 'planes#create'
# get 'planes/new', to: 'planes#new'
# get 'planes/id/edit', to: 'planes#edit'

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plane.rb
class Plane < ApplicationRecord
  include PgSearch

  belongs_to :user #:owner, class_name: "User"
  has_many :rentals
  validates :rate, presence: true
  validates :make, presence: true
  validates :description, presence: true
  validates :location, presence: true
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  #has_many :renters, through: :rentals,  class_name: "User"
  mount_uploader :picture, PictureUploader

  pg_search_scope :full_search,
    against: [ :make, :description, :location],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  after_validation :set_default_picture, if: :picture_missing?

  private

  def set_default_picture
    self.remote_picture_url = "https://chrisguillebeau.com/files/2016/10/plane.jpg"
  end

  def picture_missing?
    picture.blank?
  end
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user #:renter, class_name: "User"
  belongs_to :plane
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :planes # :owned_planes, class_name: "Plane"
  has_many :rentals
  has_many :rented_planes, through: :rentals, source: :plane


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
     # For additional fields in app/views/devise/registrations/new.html.erb
     devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

     # For additional in app/views/devise/registrations/edit.html.erb
     devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name])
   end
 end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def show
    @user = current_user
    @planes = @user.planes
    @rentals = @user.rentals
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @planes = Plane.all.limit(3)
  end
end

app/controllers/planes_controller.rb
class PlanesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present?
      @planes = Plane.full_search(params[:query])
    else
      @planes = Plane.all
    end
    @markers = @planes.where.not(latitude: nil, longitude: nil).map do |plane|
      {
        lat: plane.latitude,
        lng: plane.longitude,
        infoWindow: { content: render_to_string(partial: "../views/planes/map_box.html.erb", locals: { plane: plane }) }
      }
    end
  end

  def show
    @plane = Plane.find(params[:id])
  end

  def new
    @plane = Plane.new
      # @rental = Rental.new
  end

  def create
    @plane = Plane.new(plane_params)
    @user = current_user
    @plane.user = @user
    if @plane.valid?
      @plane.save!
      redirect_to @plane
    else
      render :new
    end
  end

  def edit
    @plane = Plane.find(params[:id])
  end

  def update
    @plane = Plane.find(params[:id])
    if @plane.update(plane_params)
      redirect_to @plane, notice: "Plane was updated"
    else
      render :edit
    end
  end

  def destroy
    @plane = Plane.find(params[:id])
    @plane.destroy
    redirect_to planes_path, notice: "Plane was deleted"
  end

  private

  def set_plane
    @plane = Plane.find(params[:plane_id])
  end

  def plane_params
    params.require(:plane).permit(:rate, :make, :description, :location, :picture)
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :set_rental, only: [:show, :update]
  before_action :authenticate_user!

  def index
    @rentals = Rental.all
  end

  def show
    @plane = @rental.plane
  end

  def new
    @plane = Plane.find(params[:plane_id])
    @rental = Rental.new
  end

  def create
    @rental = Rental.new(rental_params)
    @plane = Plane.find(params[:plane_id])
    @rental.plane = @plane

    @user = current_user
    @rental.user = @user

    if @rental.save
      redirect_to plane_path(@plane), notice: "You booked the plane succefully"
    else
      render "rentals/new"
    end
  end


  def destroy
    @rental = Rental.find(params[:id])
    @rental.destroy
    redirect_to dashboard_path

  end

private

  def set_rental
    @rental = Rental.find(params[:id])
  end

  def rental_params
      params.require(:rental).permit(:start_date, :end_date)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/show.html.erb
<div class="container dashboard-container">
  <div class="row">
    <h1>Hello, <%= @user.first_name %> <%= @user.last_name %></h1>
    <br>
    <div class="col-xs-12 col-sm-6 col-md-6">
      <h2>Here are your Planes:</h2>
      <ul>
        <% @planes.each do |item| %>
        <li>
          <%= link_to item.make, plane_path(item) %>
          <%= item.description %>
          <%= item.rate %>
          <%= item.location %>
        </li>
          <% end %>
      </ul>
    </div>

    <div class="col-xs-12 col-sm-6 col-md-6">
      <h2>Here are your bookings</h2>

      <ul>
        <% @rentals.each do |item| %>
        <li>
          <%=  link_to item.plane.make, plane_path(item) %>
          <%= item.plane.description %>
          <%= item.plane.rate %>
          <%= item.plane.location %>
          from <%= item.starts_at %>
          to <%= item.ends_at %>
          <%= item.user.first_name %>
          <%= item.user.last_name %>

          <%= link_to rental_path(item), method: :delete, data: { confirm: "Are you sure?" } do %>
          <i class="fa fa-trash"></i>
          <% end %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Book My Plane</title>
  <link href="https://fonts.googleapis.com/css?family=Hind+Guntur|Julius+Sans+One" rel="stylesheet">
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
</head>
<body>
  <%= render 'shared/navbar' %>
  <%= render 'shared/flashes' %>
  <%= yield %>
  <%= render 'shared/footer' %>

  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
  <%= javascript_pack_tag "map" %> <!-- add this line -->

</body>

</html>

app/views/pages/home.html.erb
<div class="banner banner-home" style="background-image: linear-gradient(-225deg, #101010 0%, rgba(0,36,61,0.5) 0%), url('https://images.trvl-media.com/media/content/expus/graphics/launch/home/tvly/150324_flights-hero-image_1330x742.jpg');">
  <div class="banner-content">
    <h1>BOOK MY PLANE</h1>
    <%= form_tag planes_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control home-form",
        placeholder: "where?"
      %>
    <% end %>
  </div>
</div>
<div class="wrapper">

<div id="about" class="container page-container">



  <div class="row three-steps-main">
    <div class="col-xs-12 col-sm-6 col-md-4">
      <div class="first-step column">
        <i class="fas fa-search"></i>
        <h3>Search</h3>
        <p>Just pick the one suits your needs, and our system will take care of everything you need.<br>We do our best to keep it simple!</p>

      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4">
      <div class="second-step column">
        <!-- <img class="icon" height="42" width="42" src="https://cdn3.iconfinder.com/data/icons/transportation-13/512/aircraft-512.png" /> -->
        <i class="fas fa-plane"></i>
        <h3>Book a plane</h3>
        <p>Just pick the one suits your needs, and our system will take care of everything you need.<br>We do our best to keep it simple!</p>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4">
      <div class="third-step column">
        <!-- <img class="icon" height="42" width="42" src="https://www.biddwell.com/static/landing-img/two-point-zero/landlord/Landlord-Icon-NegoitateOnRate.png" /> -->
        <i class="fas fa-wallet"></i>
        <h3>Become a PlaneLord</h3>
        <p>Just pick the one suits your needs, and our system will take care of everything you need.<br>We do our best to keep it simple!</p>

      </div>
    </div>
  </div>

  <div class="card-container">
    <h3>Recommended for you</h3>
  <div class="row card-row">
    <% @planes.each do |plane| %>
      <%= link_to plane_path(plane) do %>
        <div class="col-sm-4">
          <div class="card-wrapper">
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path plane.picture, height: 300, width: 400, crop: :fill %>');">
            </div>
              <div class="card-description">
                <h2><%= plane.make %></h2>
                <!-- $<%= plane.rate %> -->
                <%= plane.location %>
              </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

</div>
</div>

app/views/pages/show.html.erb
<<html>
<body>
  <%= render 'shared/navbar' %>
  <div>
    <a href="#">Cessan 182</a>
    <a href="#">Tommy PA 38</a>
    <a href="#">Cessna 152</a>
  </div>
  <div class="card-description">
    <p>"description here"</p>
  </div>

</body>
</html>

app/views/planes/_form.html.erb
<%= simple_form_for(@plane) do |f| %>
  <%= f.input :picture %>
  <%= f.input :picture_cache, as: :hidden %>
<% end %>

app/views/planes/_map_box.html.erb
<div id="mapbox">
    <br>
    <h3><%= link_to plane.make, plane_path(plane)%> </h3>
    <br>
    <p>Rate: $<%= plane.rate %>/day</p>
    <br>
    <p>Location: <%= plane.location %></p>
    <br>
</div>

app/views/planes/edit.html.erb
<%#= render "form" %>
      <%= simple_form_for @plane do |f| %>
        <%= f.input :rate %>
        <%= f.input :make %>
        <%= f.input :description %>
        <%= f.input :location %>
        <%= f.input :picture %>
        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>

app/views/planes/index.html.erb
<div class="main-container">
  <div class="cards-container">
    <%= form_tag planes_path, method: :get, :id => "search_form" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "enter location or model"
      %>
      <%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search button',:name => nil%>

    <% end %>
    <div class="row card-row">
      <% @planes.each do |plane| %>

        <%= link_to plane_path(plane) do %>
        <div class="col-xs-12 col-sm-6 col-md-4">
          <div class="card-wrapper">
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= cl_image_path plane.picture, height: 300, width: 400, crop: :fill %>);">
            </div>
            <div class="card-description">
              <h2><%= plane.make %></h2>
              $<%= plane.rate %>
              <%= plane.location %>
            </div>
          </div>
        </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div id="map" data-markers="<%= @markers.to_json %>">
  </div>
</div>

app/views/planes/new.html.erb
<div id="newshow">
<div class="container dashboard-container">

  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1>Plane Details</h1>

      <%= simple_form_for @plane do |f| %>
        <%= f.input :rate , placeholder: "Eg. $180", label: "Rate per day" %>
        <%= f.input :make, placeholder: "cessna 152"  %>
        <%= f.input :description, placeholder: "specifications" %>
        <%= f.input :location, placeholder: "city"  %>
        <%= f.input :picture , label: "Picture"%>
        <%= f.button :submit, class: 'btn btn-primary button'%>
      <% end %>
    </div>
  </div>
</div>
<%= link_to "Go back", @plane %>
</div>

app/views/planes/show.html.erb
<div class="responsive">
<div class="container_picture">
<div class="banner" style="background-image: url('<%= @plane.picture %>');"></div>
<div class="description">
    <h1><%= @plane.make %></h1>
    <p>$<%= @plane.rate %></p>
    <p><%= @plane.description %></p>
    <p><%= @plane.location %></p>
    <%  if current_user != @plane.user %>
    <p><%= link_to "Book this plane", new_plane_rental_path(@plane), class: "btn btn-primary btn-lg button" %></p>
    <% else %>
    <span>Delete<%= link_to plane_path, method: :delete, data: { confirm: "Are you sure?" } do %>
<i class="fa fa-trash destroy_plane"></i>
</span>
<% end %>
<span>
Edit
<%= link_to edit_plane_path(@plane),  method: :get do %>
<i class="far fa-edit edit_plane"></i>
</span>
<% end %>
<% end %>
</div>
</div>
</div>
</div>

<!--
<div class="footer">
  <div class="footer-copyright">
    Have a safe flight from the Amsterdam team <i class="fas fa-plane"></i>
  </div>
</div> -->

app/views/rentals/new.html.erb
<div class="container dashboard-container">
  <div class="row details">
    <h2>Please select the dates</h2>
  </div>
<div>
  <div class="form-wrapper" style="width: 400px; margin: 0 auto; text-align:center">
    <%= simple_form_for [@plane, @rental] do |f| %>
      <%= f.input :starts_at, as: :string, required: false, input_html: {class: "datepicker"},label: "From:"%>
      <%= f.input :ends_at, as: :string, required: false, input_html: {class: "datepicker"}, label: "Until:"%>
      <%= f.button :submit, "Book", class: "btn btn-primary button" %>
    <% end %>
  </div>
</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    Have a safe flight from the Amsterdam team <i class="fas fa-plane"></i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "plane.png", height: 70 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Become a PlaneLord", new_plane_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Find a Plane", planes_path, class: "navbar-wagon-item navbar-wagon-link" %>
       <%= link_to "Home", root_path, class: "navbar-wagon-item navbar-wagon-link" %>



      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://www.planecharacters.com/wp-content/uploads/2015/04/character-pilot-ollie-square-wpcf_400x400.jpg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to edit_user_registration_path do %>
                <!-- <i class="fa fa-user"></i> --> <%= t(".profile", default: "Edit Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to dashboard_path do %>
               <!--  <i class="fas fa-columns"></i> -->  <%= t(".settings", default: "Dashboard") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Home", root_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>